// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYnI6slSBNr_7uPClyA3M8Ez-oXqsVqw4',
    appId: '1:1006229271964:web:11a64de030977eb181c459',
    messagingSenderId: '1006229271964',
    projectId: 'vbite-canteen',
    authDomain: 'vbite-canteen.firebaseapp.com',
    storageBucket: 'vbite-canteen.appspot.com',
  );
}

